### ISSUE TITLE
lesion-predict-image padding issue 

### ISSUE THREAD

**Issue by AliceSantilli** [jcreinhold/tiramisu-brulee#20]
## 🐛 Bug

When running lesion-predict-image, the code starts predicting and throws the following error : 

```
Global seed set to 0
GPU available: False, used: False
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
2021-12-15 14:09:32,840 - py.warnings - WARNING - /Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/utils/data/dataloader.py:478: UserWarning: This DataLoader will create 16 worker processes in total. Our suggested max number of worker in current system is 8 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(

Predicting: 0it [00:00, ?it/s]2021-12-15 14:10:06,060 - py.warnings - WARNING - /Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py:172: UserWarning: Lightning couldn't infer the indices fetched for your dataloader.
  warning_cache.warn("Lightning couldn't infer the indices fetched for your dataloader.")

Traceback (most recent call last):
  File "/Users/asantilli/PycharmProjects/AWS_lambda_docker/trial.py", line 22, in <module>
    main("alice")
  File "/Users/asantilli/PycharmProjects/AWS_lambda_docker/trial.py", line 18, in main
    resutls = predict.predict_image(args=args)
  File "/Users/asantilli/PycharmProjects/AWS_lambda_docker/tiramisubrulee/tiramisu_brulee/experiment/cli/predict.py", line 197, in predict_image
    _predict(args, parser, False)
  File "/Users/asantilli/PycharmProjects/AWS_lambda_docker/tiramisubrulee/tiramisu_brulee/experiment/cli/predict.py", line 273, in _predict
    _predict_whole_image(args, model_path, model_num)
  File "/Users/asantilli/PycharmProjects/AWS_lambda_docker/tiramisubrulee/tiramisu_brulee/experiment/cli/predict.py", line 218, in _predict_whole_image
    trainer.predict(model, datamodule=dm)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 988, in predict
    return self._call_and_handle_interrupt(
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1032, in _predict_impl
    results = self._run(model, ckpt_path=self.predicted_ckpt_path)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1195, in _run
    self._dispatch()
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1273, in _dispatch
    self.training_type_plugin.start_predicting(self)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 210, in start_predicting
    self._results = trainer.run_stage()
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1284, in run_stage
    return self._run_predict()
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1346, in _run_predict
    return self.predict_loop.run()
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/prediction_loop.py", line 88, in advance
    dl_predictions, dl_batch_indices = self.epoch_loop.run(
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/loops/base.py", line 145, in run
    self.advance(*args, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 105, in advance
    self._predict_step(batch, batch_idx, dataloader_idx)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/prediction_epoch_loop.py", line 135, in _predict_step
    predictions = self.trainer.accelerator.predict_step(step_kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 252, in predict_step
    return self.training_type_plugin.predict_step(*step_kwargs.values())
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 225, in predict_step
    return self.model.predict_step(*args, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/tiramisu_brulee-0.1.36-py3.9.egg/tiramisu_brulee/experiment/seg.py", line 257, in predict_step
    return self._predict_whole_image(batch)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/tiramisu_brulee-0.1.36-py3.9.egg/tiramisu_brulee/experiment/seg.py", line 325, in _predict_whole_image
    pred_seg = self._predict_patch_image(batch)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/tiramisu_brulee-0.1.36-py3.9.egg/tiramisu_brulee/experiment/seg.py", line 332, in _predict_patch_image
    pred = self(src)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/tiramisu_brulee-0.1.36-py3.9.egg/tiramisu_brulee/experiment/seg.py", line 140, in forward
    out: Tensor = self.network(tensor)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/tiramisu_brulee-0.1.36-py3.9.egg/tiramisu_brulee/model/tiramisu.py", line 167, in forward
    out = self.first_conv(x)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/modules/container.py", line 141, in forward
    input = module(input)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/modules/padding.py", line 328, in forward
    return F.pad(input, self.padding, 'replicate')
  File "/Users/asantilli/.local/share/virtualenvs/AWS_lambda_docker-0zwPIMFV/lib/python3.9/site-packages/torch/nn/functional.py", line 4207, in _pad
    raise NotImplementedError("Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now")
NotImplementedError: Only 2D, 3D, 4D, 5D padding with non-constant padding are supported for now
Predicting:   0%|          | 0/1 [00:35<?, ?it/s]
```

## To Reproduce

Ran lesion-predict-image inline using : 

```
input_img = "S0006_PV_5mm.nii.gz"
save_filename = "save_image_test.nii.gz"
model_name = "model_test.ckpt"
args = ["--t1", str(input_img), "--out", str(save_filename), "--model-path", model_name]

results = predict.predict_image(args=args)
```

**Comment by jcreinhold** [comment]
Not sure what's going on exactly without more context about the setup, but this is likely due to the default value for one or more arguments, e.g., patch size, pseudo3d dim, pseudo3d size, etc.

Look at the predict config file generated after training for reference and pass in the corresponding values in `args` too.

**Comment by AliceSantilli** [comment]
lesion-predict-image does not take config file as input but issue was fixed by specifying the arguments in the inputs : 
args = ["--patch-size", "none", "none", "--pseudo3d-dim", "2", "--pseudo3d-size", "3", "--t1", str(input_img),
                "--out", str(save_filename), "--model-path", str(model_path), "--gpus", "1"]
